name: Almacenar credenciales

on:
  push:
    branches: [ main ]

jobs:
  run-openai-script:
    runs-on: ubuntu-latest

- name: Ejecutar archivo por lotes
      run: \run.bat
      shell: cmd
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}