on:
   workflo_dispatch

env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
	BD_PASSWORD: $${{ secrets.OPENAI_API_KEY }}
        run: python punto_2/embedding.py
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Run script
	python embedding.py
        